version: '3'

services:
  smarthome.dashboard.influxsrv:
    image: influxdb
    container_name: smarthome.dashboard.influxsrv
    restart: on-failure:3
    networks:
      - smarthome-network
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb/types.db:/usr/local/share/collectd/types.db
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    expose:
      - 8090
      - 8099
    
  smarthome.dashboard.grafana:
    image: grafana/grafana
    container_name: smarthome.dashboard.grafana
    restart: on-failure:3
    networks:
      - smarthome-network
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana-data:
  influxdb-data:

networks:
  smarthome-network:
