{
 "title": "Docker",
 "description": "Detailed metrics for containers in Docker",
 "tags": [
  "docker",
  "container"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "containerName",
    "label": "Container",
    "query": "SHOW TAG VALUES WITH KEY = \"container_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "fs_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$containerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Size history",
   "type": "graph",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fs_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$containerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "cpu",
     "measurement": "cpu_usage_system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$containerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / sec" }
   ],
   "targets": [
    {
     "alias": "in",
     "measurement": "rx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$containerName$/" }
     ]
    },
    {
     "alias": "out",
     "measurement": "tx_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$containerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes", "label": "bytes" }
   ],
   "targets": [
    {
     "alias": "usage",
     "measurement": "memory_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$containerName$/" }
     ]
    }
   ]
  }
 ]
}